name: Build notes-service

on:
    push:
        paths:
            - 'src/**'
            - 'Dockerfile'
            - 'Makefile'
            - '.github/workflows/notes-service.build.yaml'
    pull_request:
        paths:
            - 'src/**'
            - 'Dockerfile'
            - 'Makefile'
            - '.github/workflows/notes-service.build.yaml'

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set image tag
              id: vars
              run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

            - name: Build Docker image
              run: make cicd.build

            - name: Run unit tests
              run: make cicd.test.unit